services:
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    command: ["npm", "run", "db:migrate"]
    container_name: migrate
    env_file:
      - .env.prod
    volumes:
      - ./data:/app/data
    restart: "no"

  web:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    command: ["npm", "run", "start"]
    container_name: dash
    env_file:
      - .env.prod
    depends_on:
      migrate:
        condition: service_completed_successfully
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  scheduler-ui:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    command: ["npm", "run", "start:scheduler"]
    container_name: scheduler-ui
    env_file:
      - .env.prod
    depends_on:
      migrate:
        condition: service_completed_successfully
    volumes:
      - ./data:/app/data
    restart: unless-stopped
